name: qyre_test
description: Qyre test application.
version: 1.0.0+1
publish_to: none


environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  freezed: ^2.1.0+1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.1.6

flutter_gen:
  output: lib/core/generated/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
    - assets/icons/